# Numpy library 

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in array

In [7]:
arr = np.array(20)
print(arr)
print(type(arr))
print("Dimension of array =",arr.ndim)   

20
<class 'numpy.ndarray'>
Dimension of array = 0


# 1D array

In [8]:
arr = np.array([1,2,3,4])
print(arr)
print("Dimension of array =",arr.ndim)

[1 2 3 4]
Dimension of array = 1


# 2D array

In [9]:
arr = np.array([[1,2,3],[4,5,8]])
print(arr)
print("Dimension of array =",arr.ndim)

[[1 2 3]
 [4 5 8]]
Dimension of array = 2


In [10]:
arr= np.array([[[1,2,3],[4,8,8]],[[5,8,9],[8,8,3]]])
print(arr)
print("Dimension of array =",arr.ndim)

[[[1 2 3]
  [4 8 8]]

 [[5 8 9]
  [8 8 3]]]
Dimension of array = 3


In [11]:
import numpy as np
arr = np.array([[[12,5],[5,6],[55,66]]])
print(arr)
print(arr.ndim)

[[[12  5]
  [ 5  6]
  [55 66]]]
3


# creating a n dimensional array by using ndmin

In [12]:
arr = np.array([55,65,45,7], ndmin=6)
print(arr)
print("dimdension of given array is : ",arr.ndim)

[[[[[[55 65 45  7]]]]]]
dimdension of given array is :  6


In [13]:
arr = np.array([55,65,45,7], ndmin=6)
print(arr)
print("dimdension of given array is : ",arr.ndim)

[[[[[[55 65 45  7]]]]]]
dimdension of given array is :  6


# indexing in array

In [14]:
arr =np.array([1,2,3,4])
print(arr[1])

2


In [15]:
m =np.array([5,66,8,3,-87,-44,47,658,84,521,48])
print("sum of elements:",m[0]+m[2])

sum of elements: 13


# understanding the positions of index for 2d 3d 1d array cases


In [16]:
arr =np.array([[1,2,8,9],[8,7,9,2]])
print("1st row and 2nd element:",arr[0,1])

1st row and 2nd element: 2


In [17]:
arr =np.array([[1,2,8,9],[8,7,9,2]])
print("2nd row and 3rd element:",arr[1,2])

2nd row and 3rd element: 9


In [18]:
arr =np.array([[1,2,8,9],[8,7,9,2]])
print("1st row and 1st element:",arr[0,0])

1st row and 1st element: 1


In [19]:
arr =np.array([[1,2,8,9],[8,7,9,2]])
print("2nd row and 2nd element:",arr[1,1])

2nd row and 2nd element: 7


# addition of two dim array

In [20]:
arr =np.array([[1,2,8,9],[8,7,9,2]])
print("1st row 1st element:",arr[0,0])
print("2nd row 4th element:",arr[1,3])
print("sum", arr[0,0]+arr[1,3])

1st row 1st element: 1
2nd row 4th element: 2
sum 3


# access 3d array focus clearly

In [25]:
arr=np.array([[[1,2,3],[8,5,4],[2,1,3]]])
print(arr[0,0,1])
print(arr)

2
[[[1 2 3]
  [8 5 4]
  [2 1 3]]]


In [28]:
arr=np.array([[[[1,2,3],[8,5,4],[2,1,3]]]])
print(arr[0,0,0,1])

2


In [29]:
arr=np.array([[[1,2,3],[8,5,4]],[[52,5,6],[8,6,1]]])
print(arr[0,0,1])

2


In [30]:
arr=np.array([[[1,2,3],[8,5,4]],[[52,5,6],[8,6,1]]])
print(arr[1,0,1])

5
