# numpy part 2 

In [1]:
import numpy as np

In [11]:
arr = np.array([22,5,8,1,2,3,4])
print(arr)
print("Print middle three numbers",arr[2:5])
print("giving a step of one",arr[::2])

[22  5  8  1  2  3  4]
Print middle three numbers [8 1 2]
giving a step of one [22  8  2  4]


# slicing in 2d array

In [14]:
arr = np.array([[22,5,8,1],[5,8,7,9]])
print("items in second row and 8 7 9 are :",arr[1,1:4])
print("items in first row and 5 8 are :",arr[0,1:3])

items in second row and 8 7 9 are : [8 7 9]
items in first row and 5 8 are : [5 8]


# checking data type in array

In [16]:
arr = np.array([[22,5,8,1],[5,8,7,9]])
print(arr.dtype)      # int32    means integer 32 bit

int32


In [17]:
arr = np.array(['animal','dog'])
print(arr.dtype)

<U6


# creating  array with defined data type

In [20]:
arr = np.array([1,2,3,4], dtype = 'S')    # S means string
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


# create an array with data types 4 bytes integer

In [23]:
arr = np.array([1,2,3,4], dtype = 'i4')     # i = integer
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# numpy array shape

shape of an array depends on number of elements in each dimension

# print the shape of 2d array

In [26]:
arr = np.array([[22,5,8,1],[5,8,7,9]])
print(arr.shape)           # 2 rows and 4 columns

(2, 4)


In [28]:
arr = np.array([[[22,5,8,1],[5,8,7,9],[10,20,30,40]]])
print(arr.shape)

(1, 3, 4)


# joining nupy arrays

In [30]:
arr1= np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


# join 2d arrays

In [32]:
arr1= np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2) , axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [33]:
arr1= np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2) , axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# splitting of arrays

In [34]:
arr= np.array([1,2,3,4,5,6])
new = np.array_split(arr,2)
print(new)

[array([1, 2, 3]), array([4, 5, 6])]


In [35]:
arr= np.array([1,2,3,4,5,6])
new = np.array_split(arr,6)
print(new)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [36]:
arr= np.array([1,2,3,4,5,6])
new = np.array_split(arr,3)
print(new)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [37]:
arr= np.array([1,2,3,4,5,6])
new = np.array_split(arr,4)
print(new)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# ravel and flatten

converts multidimensional array into 1d array

In [39]:
arr = np.array([[[1,2],[3,4],[5,6]]])
print(arr)
print("dimension of array is :",arr.ndim)
n = arr.ravel()
print(n)
print("dimension of array is :",n.ndim)

[[[1 2]
  [3 4]
  [5 6]]]
dimension of array is : 3
[1 2 3 4 5 6]
dimension of array is : 1


In [42]:
arr = np.array([[[1,2],[3,4],[5,6]]])
print(arr)
print("dimension of array is :",arr.ndim)
n = arr.flatten()
print(n)
print("dimension of array is :",n.ndim)
print(type(n))

[[[1 2]
  [3 4]
  [5 6]]]
dimension of array is : 3
[1 2 3 4 5 6]
dimension of array is : 1
<class 'numpy.ndarray'>


In [43]:
arr = np.array([[[[1,2],[3,4],[5,6]]]])
print(arr)
print("dimension of array is :",arr.ndim)
n = arr.flatten()
print(n)
print("dimension of array is :",n.ndim)
print(type(n))

[[[[1 2]
   [3 4]
   [5 6]]]]
dimension of array is : 4
[1 2 3 4 5 6]
dimension of array is : 1
<class 'numpy.ndarray'>


# unique function

In [46]:
arr = np.array([1,2,3,4,1,2,8,9,9,8])
print(arr)
n = np.unique(arr)
print(n)

[1 2 3 4 1 2 8 9 9 8]
[1 2 3 4 8 9]


In [47]:
arr = np.array([1,2,3,4,1,2,8,9,9,8])
print(arr)
n = np.unique(arr, return_index = True)
print(n)

[1 2 3 4 1 2 8 9 9 8]
(array([1, 2, 3, 4, 8, 9]), array([0, 1, 2, 3, 6, 7], dtype=int64))


In [48]:
arr = np.array([1,2,3,4,1,2,8,9,9,8])
print(arr)
n = np.unique(arr, return_index = True, return_counts = True)
print(n)

[1 2 3 4 1 2 8 9 9 8]
(array([1, 2, 3, 4, 8, 9]), array([0, 1, 2, 3, 6, 7], dtype=int64), array([2, 2, 1, 1, 2, 2], dtype=int64))


# delete


In [4]:
import numpy as np
arr = np.array([1,2,3,4])
d = np.delete(arr,[1])

print(d)


[1 3 4]


In [5]:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr)
print('     ')
m = np.delete(arr, 1, axis=0)
print(m)

[[1 2]
 [3 4]
 [5 6]]
     
[[1 2]
 [5 6]]
